" Installed scripts
" 1. Pathogen
" 2. LatexBox
" 3. Colorscheme - molokai
" 4. vim-sensible
" 5. vim-airline
" 6. vim-autoclose -
" 7. ctrp.vim
" 8. vim-fugitive
" 9. nerdcommenter
" 10. youcompleteme
" 11. auto-pairs
" 12. tabline
" 13. vim-markdown


" Reload .vimrc if changed
autocmd! bufwritepost .vimrc source %

" Not compatible with VI
set nocompatible

" Indentation 
set autoindent
set smartindent
set cindent

" intelligent comments
set comments=sl:/*,mb:\ *,elx:\ */

" use intelligent file completion like in the bash
set wildmode=longest:full
set wildmenu

" Enable line numbers
set number

" Syntax highlighting
syntax on 

" Basic settings 
filetype plugin indent on

" Tab settings
set tabstop=4
set shiftwidth=4
set expandtab

" Timeout to Normal mode
set ttimeoutlen=50

" Remove the default mode indicator because we have airline!
set noshowmode

" Switch buffers without saving
set hidden

" Case insensitive search by default
set ignorecase

" Pathogen runtimepath management
execute pathogen#infect()
execute pathogen#helptags()

" Theme settings
colorscheme molokai
set t_Co=256
let g:molokai_original = 1
let g:rehash256 = 1
set background=dark

" Powerline fonts for vim-airline 
" Remember to set encoding in xshell
let g:airline_powerline_fonts = 1

" Airline theme to match
let g:airline_theme = "molokai"

" Airline tabs for open buffers -- Install tabline
let g:airline#extensions#tabline#enabled = 1

" Reindent the entire file
map <F7> mzgg=G`z<CR>

" Center line in Normal mode
nmap <space> zz

" Center while searching
nmap n nzz
nmap N Nzz

" Open empty files in insert mode
autocmd VimEnter * if empty(expand("%")) | startinsert | endif

" You complete me

" Vim markdown folding disabled
let g:vim_markdown_folding_disabled=1
